### ISSUE TITLE
deleteQuiz API Error: Cannot delete or update a parent row

### ISSUE THREAD

**Issue by shinsj4653** [Enwise/CandyKorean-Server#101]
- [x] 다음 이미지와 같은 오류가 뜬다.

![image](https://user-images.githubusercontent.com/49470452/211181479-ed6327e2-c6e8-41ef-9639-417412e6a0db.png)

**Comment by janghoosa** [comment]
cascade 옵션으로 같이 삭제되게 변경하여 수정
