### ISSUE TITLE
getClassesCountByCourseId : is_metaverse 가 false 인 것만 count 되도록 수정필요

### ISSUE THREAD

**Issue by shinsj4653** [Enwise/CandyKorean-Server#136]
- [x] getClassesCountByCourseId : 현재 is_metaverse 가 true 랑 false 인거 모두 count 해서, After Like Course의 class 수가 21 로 출력됨.
tutoring class 가 새로 생겨서, preimum 이 아닌 일반 class 메뉴에서는 is_metaverse 가 false 인 것만 count 되어야한다.
![image](https://user-images.githubusercontent.com/49470452/223045433-41c4b40c-7460-4f2f-9868-3625467cd1c6.png)

![image](https://user-images.githubusercontent.com/49470452/223044818-2325bdb3-bf24-4aa9-8586-fcb50a8ca9bf.png)

**Comment by janghoosa** [comment]
#132와 같은 문제로 해결했습니다
