### ISSUE TITLE
LearnedClass - assistant_id 추가

### ISSUE THREAD

**Issue by sohyun215** [Enwise/CandyKorean-Server#138]
course당 assistant가 여러 명일 수 있기 때문에 누구한테 튜터링 받았는지에 대한 정보가 필요합니다.

**Comment by janghoosa** [comment]
이거는 추가하는게 아니라 join으로 받아와야해서 새 api를 만들게요

**Comment by janghoosa** [comment]
추가하는게 구조적으로 더 나으니 추가하겠습니다...
