### ISSUE TITLE
solvedQuizs.service.ts : updateSolvedQuiz 수정 요청

### ISSUE THREAD

**Issue by shinsj4653** [Enwise/CandyKorean-Server#65]
- [ ]  is_correct를 true 값으로 수정을 하고 싶은데 여전히 false인채로 남아있음. 수정사항이 반영되지 않음
![image](https://user-images.githubusercontent.com/49470452/209366379-7249dff4-8117-4367-891f-a1aecd2498ff.png)

**Comment by janghoosa** [comment]
true, false 말고 0과 1로 해주세요
