### ISSUE TITLE
purchased_course에 튜터링 횟수 추가

### ISSUE THREAD

**Issue by sohyun215** [Enwise/CandyKorean-Server#89]
튜터링 받은 횟수 추가

**Comment by janghoosa** [comment]
받은 횟수를 추가하는 것보다 튜터링 관련 테이블을 새로 만드는게 낫겠죠?

**Comment by sohyun215** [comment]
네 그게 좋겠네요! 튜터링 받은 횟수, 날짜, 게더타운 url 추가하면 될 것 같습니다

**Comment by janghoosa** [comment]
새 테이블 말고 기존 테이블을 살려서 구현하는 걸로 하겠습니다.

- `Course`에 `is_premium` 추가
- `is_premium인 course`에 튜터링 횟수만큼인 `Class` 약 `10`개 정도 추가
- 튜터링을 들었을 경우 `learndClass`에 로그 추가

이 방식으로 프리미엄 코스(튜터링) 구현하는걸로 하죠
